# Generated by Django 3.1.7 on 2021-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute_choices_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_table', models.CharField(default='Personal', max_length=100)),
                ('list_name', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=500)),
                ('key_att', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('SN', models.IntegerField(blank=True, null=True, verbose_name='क्र.स')),
            ],
        ),
        migrations.CreateModel(
            name='Household_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_table', models.CharField(default='Household', max_length=100)),
                ('column_category', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_column', models.CharField(max_length=200, unique=True)),
                ('odk_data_type', models.CharField(max_length=200, null=True)),
                ('choice_list', models.CharField(max_length=200, null=True)),
                ('odk_question', models.CharField(max_length=200, null=True, unique=True)),
                ('datatype', models.CharField(blank=True, max_length=10, null=True)),
                ('display_name', models.CharField(max_length=500, null=True)),
                ('required', models.CharField(default='False', max_length=10)),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('is_multiple', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('SN', models.IntegerField(blank=True, null=True, verbose_name='क्र.स')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_table', models.CharField(default='Household', max_length=100)),
                ('column_category', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_column', models.CharField(max_length=200, unique=True)),
                ('odk_data_type', models.CharField(max_length=200, null=True)),
                ('choice_list', models.CharField(max_length=200, null=True)),
                ('odk_question', models.CharField(max_length=200, null=True, unique=True)),
                ('datatype', models.CharField(blank=True, max_length=10, null=True)),
                ('display_name', models.CharField(max_length=500, null=True)),
                ('required', models.CharField(default='False', max_length=10)),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('is_multiple', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('SN', models.IntegerField(blank=True, null=True, verbose_name='क्र.स')),
            ],
        ),
    ]
