# Generated by Django 3.0.3 on 2021-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210407_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
