# Generated by Django 3.0.3 on 2021-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210408_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='chapter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
